version: '3.9'
services:
  apache:
    build:
    context: ./
    dockerfile: ./dockerfile
    image: httpd:2.4
    container_name: my-apache-app
    ports:
    - '8080:80'
    volumes:
    - /:/var/www
