name: continue deployment preprod

on:
  push:
    branches:
      - pre-prod

jobs:

  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Portainer weebook pull and redeploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ secrets.PORTAINER_WEEBOOK_URL_PREPROD }}'
          method: 'POST'
          preventFailureOnNoResponse: true